In [1]:
# DEPENDENCIES
import pandas as pd
import numpy as np

In [2]:
# CSV FILES
file1_18624records = "Data/player_appearances.csv"
file2_7908records = "Data/players.csv"
file3_900records = "Data/matches.csv"

In [3]:
# READ AND VIEW CSV FILES
playerApps_df = pd.read_csv(file1_18624records) 
playerData_df = pd.read_csv(file2_7908records)
matches_df = pd.read_csv(file3_900records)
# playerApps_df.head()
# playerData_df.head().sort_values("count_tournaments", ascending = False)

# matches_df.info()
# macthes_df["result"].unique()
matches_df.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

#### Basic Data Cleaning

In [4]:
# CHANGING MATCH_DATE TO DATETIME IN ORDER TO EXTRACT THE MATCH YEAR
playerApps_df["match_date"] = pd.to_datetime(playerApps_df["match_date"])
playerApps_df["match_year"] = playerApps_df["match_date"].dt.year

# playerData_df["birth_date"] = pd.to_datetime(playerData_df["birth_date"])
# playerData_df["birth_year"] = playerData_df["match_date"].dt.year

matches_df["match_date"] = pd.to_datetime(matches_df["match_date"])
matches_df["match_year"] = matches_df["match_date"].dt.year

#### Exploratory Data Analysis

In [121]:
print("PLAYER APPEARANCES")
playerApps_df.info()
print()
print("-"*50)
print()
print("PLAYER INFORMATION")
playerData_df.info()
print("-"*50)
print()
print("WORLD CUP MATCHES - HISTORIC")
matches_df.info()

PLAYER APPEARANCES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18623 entries, 0 to 18622
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           18623 non-null  int64
 1   tournament_id    18623 non-null  object
 2   tournament_name  18623 non-null  object
 3   match_id         18623 non-null  object
 4   match_name       18623 non-null  object
 5   match_date       18623 non-null  datetime64[ns]
 6   stage_name       18623 non-null  object
 7   group_name       18623 non-null  object
 8   team_id          18623 non-null  object
 9   team_name        18623 non-null  object
 10  team_code        18623 non-null  object
 11  home_team        18623 non-null  int64
 12  away_team        18623 non-null  int64
 13  player_id        18623 non-null  object
 14  family_name      18623 non-null  object
 15  given_name       18623 non-null  object
 16  shirt_number     18623 non-null  int64
 17  position_name    18623 non-null  object
 18  position_code    18623 non-null  object
 19  starter          18623 non-null  int64
 20  substitute       18623 non-null  int64
 21  captain          18623 non-null  int64
 22  match_year       18623 non-null  int64
dtypes: datetime64[ns](1), int64(8), object(14)
memory usage: 3.3+ MB

--------------------------------------------------

PLAYER INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7907 entries, 0 to 7906
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   key_id                 7907 non-null   int64
 1   player_id              7907 non-null   object
 2   family_name            7907 non-null   object
 3   given_name             7907 non-null   object
 4   birth_date             7906 non-null   object
 5   goal_keeper            7907 non-null   int64
 6   defender               7907 non-null   int64
 7   midfielder             7907 non-null   int64
 8   forward                7907 non-null   int64
 9   count_tournaments      7907 non-null   int64
 10  list_tournaments       7907 non-null   object
 11  player_wikipedia_link  7907 non-null   object
dtypes: int64(6), object(6)
memory usage: 741.4+ KB
--------------------------------------------------

WORLD CUP MATCHES - HISTORIC
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   key_id                     900 non-null    int64
 1   tournament_id              900 non-null    object
 2   tournament_name            900 non-null    object
 3   match_id                   900 non-null    object
 4   match_name                 900 non-null    object
 5   stage_name                 900 non-null    object
 6   group_name                 900 non-null    object
 7   group_stage                900 non-null    int64
 8   knockout_stage             900 non-null    int64
 9   replayed                   900 non-null    int64
 10  replay                     900 non-null    int64
 11  match_date                 900 non-null    datetime64[ns]
 12  match_time                 900 non-null    object
 13  stadium_id                 900 non-null    object
 14  stadium_name               900 non-null    object
 15  city_name                  900 non-null    object
 16  country_name               900 non-null    object
 17  home_team_id               900 non-null    object
 18  home_team_name             900 non-null    object
 19  home_team_code             900 non-null    object
 20  away_team_id               900 non-null    object
 21  away_team_name             900 non-null    object
 22  away_team_code             900 non-null    object
 23  score                      900 non-null    object
 24  home_team_score            900 non-null    int64
 25  away_team_score            900 non-null    int64
 26  home_team_score_margin     900 non-null    int64
 27  away_team_score_margin     900 non-null    int64
 28  extra_time                 900 non-null    int64
 29  penalty_shootout           900 non-null    int64
 30  score_penalties            900 non-null    object
 31  home_team_score_penalties  900 non-null    int64
 32  away_team_score_penalties  900 non-null    int64
 33  result                     900 non-null    object
 34  home_team_win              900 non-null    int64
 35  away_team_win              900 non-null    int64
 36  draw                       900 non-null    int64
 37  match_year                 900 non-null    int64
dtypes: datetime64[ns](1), int64(17), object(20)
memory usage: 267.3+ KB

In [124]:
# 13  player_id        18623 non-null  object        
#  14  family_name      18623 non-null  object        
#  15  given_name       18623 non-null  object        

playerApps_df[["family_name", "given_name"]]

      family_name     given_name
0        CalderÃ³n        Ignacio
1            PeÃ±a        Gustavo
2           PÃ©rez          Mario
3       HernÃ¡ndez      Guillermo
4         Salgado  Horacio LÃ³pez
...           ...            ...
18618       RebiÄ‡           Ante
18619        Vida        Domagoj
18620     SubaÅ¡iÄ‡        Danijel
18621    KramariÄ‡         Andrej
18622       Pjaca          Marko

[18623 rows x 2 columns]

In [6]:
playerApps_Outcomes_df = pd.merge(playerApps_df, 
                      matches_df[["match_id", "result", "home_team_name", "away_team_name"]], 
                      on ="match_id", 
                      how ="inner")
playerApps_Outcomes_df

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,shirt_number,position_name,position_code,starter,substitute,captain,match_year,result,home_team_name,away_team_name
0,1,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,1,goal keeper,GK,1,0,0,1970,draw,Mexico,Soviet Union
1,2,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,3,defender,DF,1,0,1,1970,draw,Mexico,Soviet Union
2,3,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,5,defender,DF,1,0,0,1970,draw,Mexico,Soviet Union
3,4,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,6,midfielder,MF,1,0,0,1970,draw,Mexico,Soviet Union
4,5,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,10,forward,FW,1,0,0,1970,draw,Mexico,Soviet Union
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18618,18619,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,18,right winger,RW,1,0,0,2018,home team win,France,Croatia
18619,18620,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,21,center back,CB,1,0,0,2018,home team win,France,Croatia
18620,18621,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,23,goal keeper,GK,1,0,0,2018,home team win,France,Croatia
18621,18622,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,9,forward,FW,0,1,0,2018,home team win,France,Croatia
18622,18623,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,20,forward,FW,0,1,0,2018,home team win,France,Croatia

In [7]:
# IDENTIFYING THE STAGES INCLUDED IN THE PLAYER_APPEARANCES DATASET. 
# FRIENDLY MACTHES ARE NOT IN THIS DATASET AND WILL BE DROPPED FROM DATA SOURCES THAT DO INCLUDE THE FRIENDLY MATCHES

playerApps_Outcomes_df["stage_name"].unique()

array(['group stage', 'quarter-finals', 'semi-finals',
       'third-place match', 'final', 'second group stage', 'round of 16'],
      dtype=object)

In [8]:
total_matches = playerApps_Outcomes_df["match_id"].nunique()
total_matches

700

In [9]:
playerApps_Outcomes_df.head()
# playerApps_Outcomes_df.home_team_name.nunique() // number of home_team_names with wins = 78 teams
# playerApps_Outcomes_df.away_team_name.nunique() // number of away_team_names with wins = 81 teams

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,shirt_number,position_name,position_code,starter,substitute,captain,match_year,result,home_team_name,away_team_name
0,1,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,1,goal keeper,GK,1,0,0,1970,draw,Mexico,Soviet Union
1,2,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,3,defender,DF,1,0,1,1970,draw,Mexico,Soviet Union
2,3,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,5,defender,DF,1,0,0,1970,draw,Mexico,Soviet Union
3,4,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,6,midfielder,MF,1,0,0,1970,draw,Mexico,Soviet Union
4,5,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,10,forward,FW,1,0,0,1970,draw,Mexico,Soviet Union

In [68]:
playerApps_Outcomes_df["stage_name"].unique()

array(['group stage', 'quarter-finals', 'semi-finals',
       'third-place match', 'final', 'second group stage', 'round of 16'],
      dtype=object)

In [84]:
# IDENTIFYING PLAYERS WHO WON GAMES. 
# SINCE THIS DATA ALSO CONTAINS EACH MATCH WHERE THE PLAYER PLAYED, ALL "WINNING_PLAYER" VALUES PER MATCH PER TEAM WILL BE THE SAME 

playerApps_Outcomes_df.loc[playerApps_Outcomes_df["result"] == "home team win", "match_winning_team"] = playerApps_Outcomes_df["home_team_name"]
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["result"] == "away team win", "match_winning_team"] = playerApps_Outcomes_df["away_team_name"]
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["result"] == "draw", "match_winning_team"] = "Draw"
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["team_name"] == playerApps_Outcomes_df["match_winning_team"], "game_outcome"] = "win"
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["team_name"] != playerApps_Outcomes_df["match_winning_team"], "game_outcome"] = "loss"

# ADDING A SORT TO THE GROUP STAGES FOR ORGANIZATION

playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "group stage", "stage_name_sort"] = 1
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "second group stage", "stage_name_sort"] = 1.5
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "round of 16", "stage_name_sort"] = 2
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "quarter-finals", "stage_name_sort"] = 3
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "semi-finals", "stage_name_sort"] = 4
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "final", "stage_name_sort"] = 5
playerApps_Outcomes_df.loc[playerApps_Outcomes_df["stage_name"] == "third-place match", "stage_name_sort"] = 4.5

In [120]:
# GROUPED TEAMS BY NAME, MATCH YEAR, STAGE OF WC, AND GAME OUTCOME, WITH NUMBER OF MATCHES PLAYED
grouped_by_stage_df = pd.DataFrame(playerApps_Outcomes_df[["team_name", "stage_name", "match_id", "game_outcome", "match_year","stage_name_sort", ]].groupby(["team_name","match_year","stage_name", "game_outcome"]).nunique("match_id").sort_values(["team_name","match_year","stage_name_sort"], ascending=True))

historic_wins_df = pd.DataFrame(playerApps_Outcomes_df[["team_name", "stage_name", "match_id", "game_outcome","stage_name_sort"]].groupby("team_name")["game_outcome"].apply(lambda x: (x=="win").count()))
historic_losses_df = pd.DataFrame(playerApps_Outcomes_df[["team_name", "stage_name", "match_id", "game_outcome","stage_name_sort"]].groupby("team_name")["game_outcome"].apply(lambda x: (x=="loss").count()))
historic_wins_losses =historic_losses_df.merge(historic_wins_df,left_on="team_name", right_on="team_name", how="inner")
historic_wins_losses.rename(columns={"game_outcome_x":"losses", "game_outcome_y":"win"})
historic_wins_losses.head(40)

                        game_outcome_x  game_outcome_y
team_name
Algeria                            176             176
Angola                              42              42
Argentina                          859             859
Australia                          217             217
Austria                            215             215
Belgium                            549             549
Bolivia                             38              38
Bosnia and Herzegovina              42              42
Brazil                            1001            1001
Bulgaria                           262             262
Cameroon                           305             305
Canada                              39              39
Chile                              245             245
China                               42              42
Colombia                           254             254
Costa Rica                         247             247
Croatia                            314             314
Czech Republic                      42              42
Czechoslovakia                     140             140
Denmark                            275             275
East Germany                        76              76
Ecuador                            137             137
Egypt                               81              81
El Salvador                         77              77
England                            654             654
France                             660             660
Germany                            567             567
Ghana                              166             166
Greece                             136             136
Haiti                               36              36
Honduras                           120             120
Hungary                            115             115
Iceland                             42              42
Iran                               200             200
Iraq                                38              38
Israel                              37              37
Italy                              826             826
Ivory Coast                        125             125
Jamaica                             42              42
Japan                              291             291

Of 6,589 players who appeared in World Cup matches since 1970, 4,

In [27]:
matches_corr = matches_df.corr()
print(matches_corr.round(2))

                           key_id  group_stage  knockout_stage  replayed  \
key_id                       1.00         0.01           -0.01     -0.11
group_stage                  0.01         1.00           -1.00     -0.11
knockout_stage              -0.01        -1.00            1.00      0.11
replayed                    -0.11        -0.11            0.11      1.00
replay                      -0.11        -0.11            0.11     -0.00
home_team_score             -0.33        -0.08            0.08     -0.01
away_team_score              0.10        -0.09            0.09      0.03
home_team_score_margin      -0.33        -0.01            0.01     -0.03
away_team_score_margin       0.33         0.01           -0.01      0.03
extra_time                   0.05        -0.46            0.46      0.23
penalty_shootout             0.13        -0.32            0.32     -0.01
home_team_score_penalties    0.12        -0.30            0.30     -0.01
away_team_score_penalties    0.13        -0.30            0.30     -0.01
home_team_win               -0.27        -0.17            0.17     -0.08
away_team_win                0.32        -0.04            0.04     -0.04
draw                        -0.00         0.26           -0.26      0.14
match_year                   0.97         0.09           -0.09     -0.14

                           replay  home_team_score  away_team_score  \
key_id                      -0.11            -0.33             0.10
group_stage                 -0.11            -0.08            -0.09
knockout_stage               0.11             0.08             0.09
replayed                    -0.00            -0.01             0.03
replay                       1.00             0.02            -0.00
home_team_score              0.02             1.00             0.00
away_team_score             -0.00             0.00             1.00
home_team_score_margin       0.02             0.83            -0.56
away_team_score_margin      -0.02            -0.83             0.56
extra_time                  -0.02            -0.06             0.05
penalty_shootout            -0.01            -0.11            -0.04
home_team_score_penalties   -0.01            -0.10            -0.03
away_team_score_penalties   -0.01            -0.10            -0.03
home_team_win                0.06             0.60            -0.42
away_team_win               -0.04            -0.46             0.54
draw                        -0.03            -0.26            -0.06
match_year                  -0.14            -0.36             0.08

                           home_team_score_margin  away_team_score_margin  \
key_id                                      -0.33                    0.33
group_stage                                 -0.01                    0.01
knockout_stage                               0.01                   -0.01
replayed                                    -0.03                    0.03
replay                                       0.02                   -0.02
home_team_score                              0.83                   -0.83
away_team_score                             -0.56                    0.56
home_team_score_margin                       1.00                   -1.00
away_team_score_margin                      -1.00                    1.00
extra_time                                  -0.08                    0.08
penalty_shootout                            -0.07                    0.07
home_team_score_penalties                   -0.07                    0.07
away_team_score_penalties                   -0.07                    0.07
home_team_win                                0.73                   -0.73
away_team_win                               -0.68                    0.68
draw                                        -0.18                    0.18
match_year                                  -0.35                    0.35

                           extra_time  penalty_shootout  \
key_id                           0.05              0.13
group_stage                     -0.46             -0.32
knockout_stage                   0.46              0.32
replayed                         0.23             -0.01
replay                          -0.02             -0.01
home_team_score                 -0.06             -0.11
away_team_score                  0.05             -0.04
home_team_score_margin          -0.08             -0.07
away_team_score_margin           0.08              0.07
extra_time                       1.00              0.65
penalty_shootout                 0.65              1.00
home_team_score_penalties        0.61              0.94
away_team_score_penalties        0.62              0.95
home_team_win                    0.00              0.01
away_team_win                    0.06              0.07
draw                            -0.07             -0.09
match_year                       0.01              0.12

                           home_team_score_penalties  \
key_id                                          0.12
group_stage                                    -0.30
knockout_stage                                  0.30
replayed                                       -0.01
replay                                         -0.01
home_team_score                                -0.10
away_team_score                                -0.03
home_team_score_margin                         -0.07
away_team_score_margin                          0.07
extra_time                                      0.61
penalty_shootout                                0.94
home_team_score_penalties                       1.00
away_team_score_penalties                       0.89
home_team_win                                   0.05
away_team_win                                   0.02
draw                                           -0.08
match_year                                      0.11

                           away_team_score_penalties  home_team_win  \
key_id                                          0.13          -0.27
group_stage                                    -0.30          -0.17
knockout_stage                                  0.30           0.17
replayed                                       -0.01          -0.08
replay                                         -0.01           0.06
home_team_score                                -0.10           0.60
away_team_score                                -0.03          -0.42
home_team_score_margin                         -0.07           0.73
away_team_score_margin                          0.07          -0.73
extra_time                                      0.62           0.00
penalty_shootout                                0.95           0.01
home_team_score_penalties                       0.89           0.05
away_team_score_penalties                       1.00          -0.03
home_team_win                                  -0.03           1.00
away_team_win                                   0.11          -0.65
draw                                           -0.08          -0.55
match_year                                      0.11          -0.30

                           away_team_win  draw  match_year
key_id                              0.32 -0.00        0.97
group_stage                        -0.04  0.26        0.09
knockout_stage                      0.04 -0.26       -0.09
replayed                           -0.04  0.14       -0.14
replay                             -0.04 -0.03       -0.14
home_team_score                    -0.46 -0.26       -0.36
away_team_score                     0.54 -0.06        0.08
home_team_score_margin             -0.68 -0.18       -0.35
away_team_score_margin              0.68  0.18        0.35
extra_time                          0.06 -0.07        0.01
penalty_shootout                    0.07 -0.09        0.12
home_team_score_penalties           0.02 -0.08        0.11
away_team_score_penalties           0.11 -0.08        0.11
home_team_win                      -0.65 -0.55       -0.30
away_team_win                       1.00 -0.27        0.32
draw                               -0.27  1.00        0.03
match_year                          0.32  0.03        1.00

In [28]:
# print("PLAYER INFORMATION")
# playerData_df.describe().round(2)

# print("PLAYER APPEARANCES")
# playerApps_df.describe().round(2)

# print("MATCHES")
# matches_df.describe().round(2)

#### 20 players with World Cup Appearances since 1970 are associated with multiple teams. 

This largely stems from the end of the Soviet Union in 1991 and the resulting destabilization and shifting political boundaries in the Balkan region. 

Thriteen of these players played for West Germany prior to the unification of Germany in Aug 1990 (after that year's World Cup), afterwhich, all represented Germany in the World Cups after 1990. Similarly, two players played for the Soviet Union in 1990, and represented Russia in 1994. 
    
Four players who played for Yugoslavia in the 1990s went on to play for different countries during the 20 years in which:
The Socialist Federal Republic of Yugoslavia was dissolved and re-founded as the Federal Republic of Yugoslavia (1992). The Federal Republic of Yugoslavia was transformed into the State Union of Serbia and Montenegro (2003) which existed until Montenegro seceded (2006), creating two independent nations. Oh, and also during this time, the Bosnian Wars broke out, during which Croatia's borders with Yugoslavia / Serbia and Montenegro shifted. One player played for Serbia and Montenegro in 2006 and then for Serbia in 2010

In [29]:
# GROUP PLAYERS BY NUMBER OF TEAM IDS
playersTeamIds_df = pd.DataFrame(playerApps_df.groupby("player_id").nunique("team_id"))
playersTeamIds_df2 = pd.DataFrame(playerApps_df.groupby(["player_id", "match_year"]).nunique("team_id"))
# playersTeamIds_df["team_id"].sort_values(ascending = False)
# playersTeamIds_df.describe().round(2)
# playersTeamIds_df.dtypes()
# playersTeamIds_df.info()
# players_multipleTeams = len(playersTeamIds_df[playersTeamIds_df["team_id"] >1])

# players_multipleTeams_df = playersTeamIds_df[playersTeamIds_df[playersTeamIds_df["team_id"] >1]]
# players_multipleTeams_df
# print(players_multipleTeams)
playersTeamIds_df3 = playersTeamIds_df[playersTeamIds_df["team_id"] >1]
playersTeamIds_df3[["team_id", "match_year"]]

playersMultiTeams_df = pd.merge(playersTeamIds_df3, playerApps_df[["player_id", "team_id", "team_name", "match_year"]], on="player_id", how="left")
playersMultiTeams_df2 = playersMultiTeams_df[["player_id","team_id_y", "team_name_y", "match_year_y"]].drop_duplicates()
playersMultiTeams_df2.sort_values(["player_id","match_year_y"], ascending = True)

# playersMultiTeams_df2.groupby(["team_name_y", "match_year_y"]).nunique("player_id")
# playersMultiTeams_df2.groupby(["match_year_y"]).nunique("player_id")
playersMultiTeams_df2.groupby(["player_id", "match_year_y", "team_name_y"]).nunique("match_year_y").sort_values(["player_id", "match_year_y"], ascending=True)

                                              team_id_y
player_id match_year_y team_name_y
P-00876   1990         West Germany                   1
          1994         Germany                        1
          1998         Germany                        1
P-01057   1990         West Germany                   1
          1994         Germany                        1
          1998         Germany                        1
P-01456   1990         West Germany                   1
          1994         Germany                        1
P-01993   1982         West Germany                   1
          1986         West Germany                   1
          1990         West Germany                   1
          1994         Germany                        1
          1998         Germany                        1
P-02228   1990         West Germany                   1
          1994         Germany                        1
P-02621   1990         West Germany                   1
          1998         Germany                        1
P-06023   1990         Soviet Union                   1
          1994         Russia                         1
P-06204   1998         Yugoslavia                     1
          2006         Serbia and Montenegro          1
          2010         Serbia                         1
P-06449   1990         West Germany                   1
          1998         Germany                        1
P-07217   1986         West Germany                   1
          1990         West Germany                   1
          1994         Germany                        1
P-07240   1986         West Germany                   1
          1990         West Germany                   1
          1994         Germany                        1
P-07255   1990         West Germany                   1
          1994         Germany                        1
P-07393   1986         West Germany                   1
          1990         West Germany                   1
          1994         Germany                        1
P-07639   1990         Yugoslavia                     1
          1998         Croatia                        1
          2002         Croatia                        1
P-08330   1998         Yugoslavia                     1
          2006         Serbia and Montenegro          1
P-08408   1990         West Germany                   1
          1994         Germany                        1
          1998         Germany                        1
P-08435   1990         Soviet Union                   1
          1994         Russia                         1
P-08556   1990         Yugoslavia                     1
          1998         Croatia                        1
          2002         Croatia                        1
P-09048   2006         Serbia and Montenegro          1
          2010         Serbia                         1
P-09300   1990         West Germany                   1
          1994         Germany                        1
          1998         Germany                        1

In [30]:
# GROUP PLAYERS BY YEAR
players_by_year_df = playerApps_df.groupby("match_year").nunique("player_id")
# players_by_year_df.info()
players_by_year_df2 = players_by_year_df[["match_id","team_id","player_id"]]
players_by_year_df2

            match_id  team_id  player_id
match_year
1970              32       16        275
1974              38       16        265
1978              38       16        278
1982              52       24        396
1986              52       24        413
1990              52       24        413
1994              52       24        427
1998              64       32        573
2002              64       32        581
2006              64       32        599
2010              64       32        599
2014              64       32        607
2018              64       32        604

In [31]:
player_total_appearances = playerApps_df.groupby("match_year").nunique("player_id")

In [32]:
teams_2022 = ['Qatar', 'Netherlands', 'Senegal', 'Ecuador', 
            'England', 'United States', 'Wales', 'Iran', 
            'Argentina', 'Poland', 'Mexico', 'Saudi Arabia', 
            'France', 'Denmark', 'Tunisia', 'Australia', 
            'Germany', 'Spain', 'Japan', 'Costa Rica', 
            'Belgium', 'Croatia', 'Canada', 'Morocco', 
            'Brazil', 'Switzerland', 'Serbia', 'Cameroon', 
            'Portugal', 'Uruguay', 'Ghana', 'Korea Republic']

In [33]:
# looking at only countries/(historic) players who will be playing in the 2022 world cup

history = playerApps_df[(playerApps_df['team_name'].isin(teams_2022))]
history

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute,captain,match_year
0,1,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,P-02951,CalderÃ³n,Ignacio,1,goal keeper,GK,1,0,0,1970
1,2,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,P-09033,PeÃ±a,Gustavo,3,defender,DF,1,0,1,1970
2,3,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,P-02770,PÃ©rez,Mario,5,defender,DF,1,0,0,1970
3,4,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,P-04709,HernÃ¡ndez,Guillermo,6,midfielder,MF,1,0,0,1970
4,5,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,P-01956,Salgado,Horacio LÃ³pez,10,forward,FW,1,0,0,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18618,18619,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,P-03363,RebiÄ‡,Ante,18,right winger,RW,1,0,0,2018
18619,18620,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,P-06323,Vida,Domagoj,21,center back,CB,1,0,0,2018
18620,18621,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,P-08712,SubaÅ¡iÄ‡,Danijel,23,goal keeper,GK,1,0,0,2018
18621,18622,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,P-03779,KramariÄ‡,Andrej,9,forward,FW,0,1,0,2018
18622,18623,WC-2018,2018 FIFA World Cup,M-2018-64,France v Croatia,2018-07-15,final,not applicable,T-17,Croatia,...,P-08991,Pjaca,Marko,20,forward,FW,0,1,0,2018