In [27]:
# Import dependencies
import pandas as pd
import numpy as np

In [28]:
#Read in csv files
matches_features_df= pd.read_csv('Data/bookings.csv')
goal_features_df= pd.read_csv('Data/goals.csv')

In [29]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [30]:
matches_features_df.head()

   key_id booking_id tournament_id      tournament_name   match_id             match_name  match_date   stage_name group_name team_id     team_name team_code  home_team  away_team player_id family_name given_name  shirt_number minute_label  minute_regulation  minute_stoppage match_period  yellow_card  red_card  second_yellow_card  sending_off
0       1     B-0001       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union  1970-05-31  group stage    Group 1    T-69  Soviet Union       SUN          0          1   P-07448    Asatiani      Kakhi            11          30'                 30                0   first half            1         0                   0            0
1       2     B-0002       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union  1970-05-31  group stage    Group 1    T-69  Soviet Union       SUN          0          1   P-07350       Nodia       Givi            19          31'                 31                0   first half            1         0                   0            0
2       3     B-0003       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union  1970-05-31  group stage    Group 1    T-69  Soviet Union       SUN          0          1   P-00603     Lovchev     Evgeny             6          34'                 34                0   first half            1         0                   0            0
3       4     B-0004       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union  1970-05-31  group stage    Group 1    T-44        Mexico       MEX          1          0   P-09033        Peña    Gustavo             3          60'                 60                0  second half            1         0                   0            0
4       5     B-0005       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union  1970-05-31  group stage    Group 1    T-69  Soviet Union       SUN          0          1   P-04868     Logofet    Gennady             7          72'                 72                0  second half            1         0                   0            0

In [31]:
goal_features_df

      key_id goal_id tournament_id      tournament_name   match_id        match_name  match_date   stage_name      group_name team_id team_name team_code  home_team  away_team player_id family_name given_name  shirt_number player_team_id player_team_name player_team_code minute_label  minute_regulation  minute_stoppage match_period  own_goal  penalty
0          1  G-0001       WC-1930  1930 FIFA World Cup  M-1930-01   France v Mexico  1930-07-13  group stage         Group 1    T-28    France       FRA          1          0   P-09831     Laurent     Lucien             0           T-28           France              FRA          19'                 19                0   first half         0        0
1          2  G-0002       WC-1930  1930 FIFA World Cup  M-1930-01   France v Mexico  1930-07-13  group stage         Group 1    T-28    France       FRA          1          0   P-05670   Langiller     Marcel             0           T-28           France              FRA          40'                 40                0   first half         0        0
2          3  G-0003       WC-1930  1930 FIFA World Cup  M-1930-01   France v Mexico  1930-07-13  group stage         Group 1    T-28    France       FRA          1          0   P-07295   Maschinot      André             0           T-28           France              FRA          43'                 43                0   first half         0        0
3          4  G-0004       WC-1930  1930 FIFA World Cup  M-1930-01   France v Mexico  1930-07-13  group stage         Group 1    T-28    France       FRA          1          0   P-07295   Maschinot      André             0           T-28           France              FRA          87'                 87                0  second half         0        0
4          5  G-0005       WC-1930  1930 FIFA World Cup  M-1930-01   France v Mexico  1930-07-13  group stage         Group 1    T-44    Mexico       MEX          0          1   P-03952     Carreño       Juan             0           T-44           Mexico              MEX          70'                 70                0  second half         0        0
...      ...     ...           ...                  ...        ...               ...         ...          ...             ...     ...       ...       ...        ...        ...       ...         ...        ...           ...            ...              ...              ...          ...                ...              ...          ...       ...      ...
2543    2544  G-2544       WC-2018  2018 FIFA World Cup  M-2018-64  France v Croatia  2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-06083       Pogba       Paul             6           T-28           France              FRA          59'                 59                0  second half         0        0
2544    2545  G-2545       WC-2018  2018 FIFA World Cup  M-2018-64  France v Croatia  2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-02842      Mbappé     Kylian            10           T-28           France              FRA          65'                 65                0  second half         0        0
2545    2546  G-2546       WC-2018  2018 FIFA World Cup  M-2018-64  France v Croatia  2018-07-15        final  not applicable    T-17   Croatia       HRV          0          1   P-04888     Perišić       Ivan             4           T-17          Croatia              HRV          28'                 28                0   first half         0        0
2546    2547  G-2547       WC-2018  2018 FIFA World Cup  M-2018-64  France v Croatia  2018-07-15        final  not applicable    T-17   Croatia       HRV          0          1   P-09489   Mandžukić      Mario            17           T-17          Croatia              HRV          69'                 69                0  second half         0        0
2547    2548  G-2548       WC-2018  2018 FIFA World Cup  M-2018-64  France v Croatia  2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-09489   Mandžukić      Mario            17           T-17          Croatia              HRV          18'                 18                0   first half         1        0

[2548 rows x 27 columns]

In [32]:
# Filter matches_features dataframe to have match date >= 1970
matches_features_df['match_date'] = pd.to_datetime(matches_features_df['match_date'])

In [33]:
matches_features_df['year'] = matches_features_df['match_date'].dt.year

In [34]:
matches_features_df = matches_features_df[matches_features_df['year']>=1970]

In [35]:
#Get the shape of matches df
matches_features_df.shape

(2466, 27)

In [36]:
#Filter goal_features dataframe to have match date >= 1970
goal_features_df['match_date'] = pd.to_datetime(goal_features_df['match_date'])

In [37]:
goal_features_df['year'] = goal_features_df['match_date'].dt.year

In [38]:
goal_features_df = goal_features_df[goal_features_df['year']>=1970]

In [39]:
# In match_features_df, create average number of cards per game by match per country

In [40]:
matches_features_df

      key_id booking_id tournament_id      tournament_name   match_id             match_name match_date         stage_name      group_name team_id     team_name team_code  home_team  away_team player_id family_name given_name  shirt_number minute_label  minute_regulation  minute_stoppage                match_period  yellow_card  red_card  second_yellow_card  sending_off  year
0          1     B-0001       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union 1970-05-31        group stage         Group 1    T-69  Soviet Union       SUN          0          1   P-07448    Asatiani      Kakhi            11          30'                 30                0                  first half            1         0                   0            0  1970
1          2     B-0002       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union 1970-05-31        group stage         Group 1    T-69  Soviet Union       SUN          0          1   P-07350       Nodia       Givi            19          31'                 31                0                  first half            1         0                   0            0  1970
2          3     B-0003       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union 1970-05-31        group stage         Group 1    T-69  Soviet Union       SUN          0          1   P-00603     Lovchev     Evgeny             6          34'                 34                0                  first half            1         0                   0            0  1970
3          4     B-0004       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union 1970-05-31        group stage         Group 1    T-44        Mexico       MEX          1          0   P-09033        Peña    Gustavo             3          60'                 60                0                 second half            1         0                   0            0  1970
4          5     B-0005       WC-1970  1970 FIFA World Cup  M-1970-01  Mexico v Soviet Union 1970-05-31        group stage         Group 1    T-69  Soviet Union       SUN          0          1   P-04868     Logofet    Gennady             7          72'                 72                0                 second half            1         0                   0            0  1970
...      ...        ...           ...                  ...        ...                    ...        ...                ...             ...     ...           ...       ...        ...        ...       ...         ...        ...           ...          ...                ...              ...                         ...          ...       ...                 ...          ...   ...
2461    2462     B-2462       WC-2018  2018 FIFA World Cup  M-2018-63      Belgium v England 2018-07-14  third-place match  not applicable    T-27       England       ENG          0          1   P-03540     Maguire      Harry             6          76'                 76                0                 second half            1         0                   0            0  2018
2462    2463     B-2463       WC-2018  2018 FIFA World Cup  M-2018-63      Belgium v England 2018-07-14  third-place match  not applicable    T-06       Belgium       BEL          1          0   P-05396      Witsel       Axel             6       90'+3'                 90                3  second half, stoppage time            1         0                   0            0  2018
2463    2464     B-2464       WC-2018  2018 FIFA World Cup  M-2018-64       France v Croatia 2018-07-15              final  not applicable    T-28        France       FRA          1          0   P-01366       Kanté     N'Golo            13          27'                 27                0                  first half            1         0                   0            0  2018
2464    2465     B-2465       WC-2018  2018 FIFA World Cup  M-2018-64       France v Croatia 2018-07-15              final  not applicable    T-28        France       FRA          1          0   P-09409   Hernandez      Lucas            21          41'                 41                0                  first half            1         0                   0            0  2018
2465    2466     B-2466       WC-2018  2018 FIFA World Cup  M-2018-64       France v Croatia 2018-07-15              final  not applicable    T-17       Croatia       HRV          0          1   P-04415    Vrsaljko       Šime             2       90'+2'                 90                2  second half, stoppage time            1         0                   0            0  2018

[2466 rows x 27 columns]

In [42]:
#Group the matches and get the average of the yellow cards 
#Divide matches into team_name and assign yellow card to team who recv'd yellow card; get the count and average

In [81]:
df_divide_match = matches_features_df.groupby('team_name')['yellow_card'].agg(['count','mean']).reset_index()

In [82]:
df_divide_match.head()

   team_name  count      mean
0    Algeria     17  1.000000
1     Angola     11  1.000000
2  Argentina    123  0.959350
3  Australia     35  0.914286
4    Austria     24  0.958333

In [83]:
df_divide_match.rename(columns={"team_name": "Team_Name", "count": "Yellow_Card_Count", "mean": "Avg_Yellow_Card"},inplace=True)

In [84]:
#Print new dataframe
df_divide_match

                 Team_Name  Yellow_Card_Count  Avg_Yellow_Card
0                  Algeria                 17         1.000000
1                   Angola                 11         1.000000
2                Argentina                123         0.959350
3                Australia                 35         0.914286
4                  Austria                 24         0.958333
5                  Belgium                 52         0.961538
6                  Bolivia                  9         0.888889
7   Bosnia and Herzegovina                  3         1.000000
8                   Brazil                102         0.950980
9                 Bulgaria                 37         1.000000
10                Cameroon                 55         0.872727
11                  Canada                  3         1.000000
12                   Chile                 45         0.977778
13                   China                  6         0.833333
14                Colombia                 32         0.968750
15              Costa Rica                 37         1.000000
16                 Croatia                 54         0.962963
17          Czech Republic                  8         0.875000
18          Czechoslovakia                 19         0.947368
19                 Denmark                 40         0.950000
20            East Germany                 10         1.000000
21                 Ecuador                 24         0.958333
22                   Egypt                  9         1.000000
23             El Salvador                  9         1.000000
24                 England                 60         0.950000
25                  France                 75         0.933333
26                 Germany                 79         0.987342
27                   Ghana                 35         1.000000
28                  Greece                 21         1.000000
29                   Haiti                  3         1.000000
30                Honduras                 16         0.937500
31                 Hungary                  8         0.750000
32                 Iceland                  3         1.000000
33                    Iran                 22         1.000000
34                    Iraq                  9         1.000000
35                  Israel                  4         1.000000
36                   Italy                 98         0.948980
37             Ivory Coast                 21         1.000000
38                 Jamaica                  6         1.000000
39                   Japan                 36         1.000000
40                  Kuwait                  3         1.000000
41                  Mexico                 85         0.964706
42                 Morocco                 27         1.000000
43             Netherlands                101         0.970297
44             New Zealand                  6         1.000000
45                 Nigeria                 32         0.968750
46             North Korea                  2         1.000000
47        Northern Ireland                 10         0.900000
48                  Norway                 13         1.000000
49                  Panama                 11         1.000000
50                Paraguay                 42         0.976190
51                    Peru                 10         1.000000
52                  Poland                 45         1.000000
53                Portugal                 54         0.944444
54     Republic of Ireland                 16         1.000000
55                 Romania                 33         0.969697
56                  Russia                 30         1.000000
57            Saudi Arabia                 24         0.958333
58                Scotland                 18         0.944444
59                 Senegal                 21         0.952381
60                  Serbia                 19         1.000000
61   Serbia and Montenegro                 13         0.923077
62                Slovakia                 11         1.000000
63                Slovenia                 20         0.950000
64            South Africa                 23         0.913043
65             South Korea                 74         0.986486
66            Soviet Union                 18         0.944444
67                   Spain                 66         0.984848
68                  Sweden                 52         0.980769
69             Switzerland                 42         0.952381
70                    Togo                 10         1.000000
71     Trinidad and Tobago                 10         1.000000
72                 Tunisia                 34         1.000000
73                  Turkey                 20         0.950000
74                 Ukraine                 13         0.923077
75    United Arab Emirates                  7         1.000000
76           United States                 54         0.962963
77                 Uruguay                 68         0.941176
78            West Germany                 37         0.945946
79              Yugoslavia                 29         1.000000
80                   Zaire                  3         0.666667

In [56]:
# In goal_features_df, likelihood a violation would be commited

In [85]:
#Likelihood of violation was taken by mean of the minute regulation
y = goal_features_df.groupby('team_name')['minute_regulation'].agg(['count','mean'])

In [86]:
df1 = pd.DataFrame(y)

df1 = df1.reset_index()
df1.columns = ['Team_Name','Count_Violation','Likelihood_Violation']

In [87]:
df1

                 Team_Name  Count_Violation  Likelihood_Violation
0                  Algeria               13             47.153846
1                   Angola                1             60.000000
2                Argentina              106             49.226415
3                Australia               13             57.153846
4                  Austria               17             62.588235
5                  Belgium               60             52.683333
6                  Bolivia                1             67.000000
7   Bosnia and Herzegovina                4             62.500000
8                   Brazil              145             51.696552
9                 Bulgaria               20             53.950000
10                Cameroon               18             60.722222
11                   Chile               18             50.722222
12                Colombia               27             65.407407
13              Costa Rica               19             58.947368
14                 Croatia               35             56.085714
15          Czech Republic                3             39.000000
16          Czechoslovakia               14             47.785714
17                 Denmark               30             44.433333
18            East Germany                5             55.200000
19                 Ecuador               10             43.000000
20                   Egypt                3             59.333333
21             El Salvador                1             64.000000
22                 England               61             45.950820
23                  France               82             54.121951
24                 Germany               81             50.827160
25                   Ghana               13             50.769231
26                  Greece                5             67.400000
27                   Haiti                2             54.500000
28                Honduras                3             33.000000
29                 Hungary               17             48.411765
30                 Iceland                2             49.500000
31                    Iran                9             66.444444
32                    Iraq                1             59.000000
33                  Israel                1             56.000000
34                   Italy               90             53.355556
35             Ivory Coast               13             60.153846
36                 Jamaica                3             46.000000
37                   Japan               20             47.950000
38                  Kuwait                2             66.000000
39                  Mexico               47             52.021277
40                 Morocco               14             43.428571
41             Netherlands               84             52.904762
42             New Zealand                4             53.750000
43                 Nigeria               23             41.608696
44             North Korea                1             89.000000
45        Northern Ireland                7             40.857143
46                  Norway                6             68.000000
47                  Panama                2             55.500000
48                Paraguay               18             54.444444
49                    Peru               20             55.400000
50                  Poland               41             45.926829
51                Portugal               32             53.062500
52     Republic of Ireland               10             62.600000
53                 Romania               22             55.272727
54                  Russia               24             55.666667
55            Saudi Arabia               11             50.454545
56                Scotland               21             44.190476
57                 Senegal               11             44.181818
58                  Serbia                4             45.750000
59   Serbia and Montenegro                2             15.000000
60                Slovakia                5             65.400000
61                Slovenia                5             52.200000
62            South Africa               11             46.545455
63             South Korea               34             64.029412
64            Soviet Union               29             51.931034
65                   Spain               79             52.088608
66                  Sweden               42             55.000000
67             Switzerland               22             55.681818
68                    Togo                1             31.000000
69                 Tunisia               13             48.538462
70                  Turkey               10             35.300000
71                 Ukraine                5             48.000000
72    United Arab Emirates                2             34.000000
73           United States               25             53.640000
74                 Uruguay               35             53.742857
75            West Germany               75             56.266667
76              Yugoslavia               27             45.333333

In [60]:
goal_features_df

      key_id goal_id tournament_id      tournament_name   match_id         match_name match_date   stage_name      group_name team_id team_name team_code  home_team  away_team player_id family_name given_name  shirt_number player_team_id player_team_name player_team_code minute_label  minute_regulation  minute_stoppage match_period  own_goal  penalty  year
756      757  G-0757       WC-1970  1970 FIFA World Cup  M-1970-02   Uruguay v Israel 1970-06-02  group stage         Group 2    T-80   Uruguay       URY          1          0   P-06360     Maneiro       Ildo            10           T-80          Uruguay              URY          23'                 23                0   first half         0        0  1970
757      758  G-0758       WC-1970  1970 FIFA World Cup  M-1970-02   Uruguay v Israel 1970-06-02  group stage         Group 2    T-80   Uruguay       URY          1          0   P-02448      Mujica       Juan             6           T-80          Uruguay              URY          50'                 50                0  second half         0        0  1970
758      759  G-0759       WC-1970  1970 FIFA World Cup  M-1970-03  England v Romania 1970-06-02  group stage         Group 3    T-27   England       ENG          1          0   P-03234       Hurst      Geoff            10           T-27          England              ENG          65'                 65                0  second half         0        0  1970
759      760  G-0760       WC-1970  1970 FIFA World Cup  M-1970-04    Peru v Bulgaria 1970-06-02  group stage         Group 4    T-54      Peru       PER          1          0   P-02248    Gallardo    Alberto            11           T-54             Peru              PER          50'                 50                0  second half         0        0  1970
760      761  G-0761       WC-1970  1970 FIFA World Cup  M-1970-04    Peru v Bulgaria 1970-06-02  group stage         Group 4    T-54      Peru       PER          1          0   P-08318   Chumpitaz     Héctor             4           T-54             Peru              PER          55'                 55                0  second half         0        0  1970
...      ...     ...           ...                  ...        ...                ...        ...          ...             ...     ...       ...       ...        ...        ...       ...         ...        ...           ...            ...              ...              ...          ...                ...              ...          ...       ...      ...   ...
2543    2544  G-2544       WC-2018  2018 FIFA World Cup  M-2018-64   France v Croatia 2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-06083       Pogba       Paul             6           T-28           France              FRA          59'                 59                0  second half         0        0  2018
2544    2545  G-2545       WC-2018  2018 FIFA World Cup  M-2018-64   France v Croatia 2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-02842      Mbappé     Kylian            10           T-28           France              FRA          65'                 65                0  second half         0        0  2018
2545    2546  G-2546       WC-2018  2018 FIFA World Cup  M-2018-64   France v Croatia 2018-07-15        final  not applicable    T-17   Croatia       HRV          0          1   P-04888     Perišić       Ivan             4           T-17          Croatia              HRV          28'                 28                0   first half         0        0  2018
2546    2547  G-2547       WC-2018  2018 FIFA World Cup  M-2018-64   France v Croatia 2018-07-15        final  not applicable    T-17   Croatia       HRV          0          1   P-09489   Mandžukić      Mario            17           T-17          Croatia              HRV          69'                 69                0  second half         0        0  2018
2547    2548  G-2548       WC-2018  2018 FIFA World Cup  M-2018-64   France v Croatia 2018-07-15        final  not applicable    T-28    France       FRA          1          0   P-09489   Mandžukić      Mario            17           T-17          Croatia              HRV          18'                 18                0   first half         1        0  2018

[1792 rows x 28 columns]

In [61]:
# Combine the dataframes together

In [88]:
df_merged = pd.merge(df_divide_match,df1,on='Team_Name')

In [89]:
df_merged

                 Team_Name  Yellow_Card_Count  Avg_Yellow_Card  Count_Violation  Likelihood_Violation
0                  Algeria                 17         1.000000               13             47.153846
1                   Angola                 11         1.000000                1             60.000000
2                Argentina                123         0.959350              106             49.226415
3                Australia                 35         0.914286               13             57.153846
4                  Austria                 24         0.958333               17             62.588235
5                  Belgium                 52         0.961538               60             52.683333
6                  Bolivia                  9         0.888889                1             67.000000
7   Bosnia and Herzegovina                  3         1.000000                4             62.500000
8                   Brazil                102         0.950980              145             51.696552
9                 Bulgaria                 37         1.000000               20             53.950000
10                Cameroon                 55         0.872727               18             60.722222
11                   Chile                 45         0.977778               18             50.722222
12                Colombia                 32         0.968750               27             65.407407
13              Costa Rica                 37         1.000000               19             58.947368
14                 Croatia                 54         0.962963               35             56.085714
15          Czech Republic                  8         0.875000                3             39.000000
16          Czechoslovakia                 19         0.947368               14             47.785714
17                 Denmark                 40         0.950000               30             44.433333
18            East Germany                 10         1.000000                5             55.200000
19                 Ecuador                 24         0.958333               10             43.000000
20                   Egypt                  9         1.000000                3             59.333333
21             El Salvador                  9         1.000000                1             64.000000
22                 England                 60         0.950000               61             45.950820
23                  France                 75         0.933333               82             54.121951
24                 Germany                 79         0.987342               81             50.827160
25                   Ghana                 35         1.000000               13             50.769231
26                  Greece                 21         1.000000                5             67.400000
27                   Haiti                  3         1.000000                2             54.500000
28                Honduras                 16         0.937500                3             33.000000
29                 Hungary                  8         0.750000               17             48.411765
30                 Iceland                  3         1.000000                2             49.500000
31                    Iran                 22         1.000000                9             66.444444
32                    Iraq                  9         1.000000                1             59.000000
33                  Israel                  4         1.000000                1             56.000000
34                   Italy                 98         0.948980               90             53.355556
35             Ivory Coast                 21         1.000000               13             60.153846
36                 Jamaica                  6         1.000000                3             46.000000
37                   Japan                 36         1.000000               20             47.950000
38                  Kuwait                  3         1.000000                2             66.000000
39                  Mexico                 85         0.964706               47             52.021277
40                 Morocco                 27         1.000000               14             43.428571
41             Netherlands                101         0.970297               84             52.904762
42             New Zealand                  6         1.000000                4             53.750000
43                 Nigeria                 32         0.968750               23             41.608696
44             North Korea                  2         1.000000                1             89.000000
45        Northern Ireland                 10         0.900000                7             40.857143
46                  Norway                 13         1.000000                6             68.000000
47                  Panama                 11         1.000000                2             55.500000
48                Paraguay                 42         0.976190               18             54.444444
49                    Peru                 10         1.000000               20             55.400000
50                  Poland                 45         1.000000               41             45.926829
51                Portugal                 54         0.944444               32             53.062500
52     Republic of Ireland                 16         1.000000               10             62.600000
53                 Romania                 33         0.969697               22             55.272727
54                  Russia                 30         1.000000               24             55.666667
55            Saudi Arabia                 24         0.958333               11             50.454545
56                Scotland                 18         0.944444               21             44.190476
57                 Senegal                 21         0.952381               11             44.181818
58                  Serbia                 19         1.000000                4             45.750000
59   Serbia and Montenegro                 13         0.923077                2             15.000000
60                Slovakia                 11         1.000000                5             65.400000
61                Slovenia                 20         0.950000                5             52.200000
62            South Africa                 23         0.913043               11             46.545455
63             South Korea                 74         0.986486               34             64.029412
64            Soviet Union                 18         0.944444               29             51.931034
65                   Spain                 66         0.984848               79             52.088608
66                  Sweden                 52         0.980769               42             55.000000
67             Switzerland                 42         0.952381               22             55.681818
68                    Togo                 10         1.000000                1             31.000000
69                 Tunisia                 34         1.000000               13             48.538462
70                  Turkey                 20         0.950000               10             35.300000
71                 Ukraine                 13         0.923077                5             48.000000
72    United Arab Emirates                  7         1.000000                2             34.000000
73           United States                 54         0.962963               25             53.640000
74                 Uruguay                 68         0.941176               35             53.742857
75            West Germany                 37         0.945946               75             56.266667
76              Yugoslavia                 29         1.000000               27             45.333333